name: Sync with upstream repository

on:
  schedule:
    # Ejecutar automáticamente cada 6 horas
    cron: "*/5 * * * *"
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Configurar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar git con un usuario genérico
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      # Agregar el repositorio original (upstream) como remoto
      - name: Add upstream repository
        run: git remote add upstream https://github.com/TonyEspinosa/LuckyNear.git

      # Obtener cambios del repositorio original
      - name: Fetch upstream changes
        run: git fetch upstream

      # Fusionar cambios en la rama main
      - name: Merge upstream/main
        run: |
          git checkout main
          git merge upstream/main --no-edit

      # Subir los cambios al repositorio en GitHub
      - name: Push changes to origin
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
